here::i_am("Code/Figure10.R")

# ============================================================
# Generate Figure 10(a)--(c):
#   Figure 10(a): Beijing
#   Figure 10(b): Shanghai
#   Figure 10(c): Hong Kong
#
# Required inputs:
#   Data/GHCNv4.xlsx
#   Data/Valid/assimilation_Beijing.csv
#   Data/Valid/assimilation_Shanghai.csv
#   Data/Valid/assimilation_HongKong.csv
#
# The validation CSV files are generated by Code/Figure9d.R and
# contain the complete annual assimilation output. Figure 10
# uses only years for which GHCN, assimilated, LME, and calibrated
# REACHES values are all available, ensuring an identical
# comparison period for all three methods.
#
# Outputs:
#   Output/Figure10/Figure10a.png
#   Output/Figure10/Figure10b.png
#   Output/Figure10/Figure10c.png
#   Output/Figure10/Figure10_metrics.csv
#   Output/Figure10/Figure10_correlations.csv
#   Output/Figure10/Figure10_plot_data.csv
# ============================================================

library(readxl)
library(dplyr)
library(tidyr)
library(readr)
library(ggplot2)

# ------------------------------------------------------------
# 1. Paths and display settings
# ------------------------------------------------------------

ghcn_file <- here::here(
  "Data",
  "GHCNv4.xlsx"
)

validation_dir <- here::here(
  "Data",
  "Valid"
)

output_dir <- here::here(
  "Output",
  "Figure10"
)

dir.create(
  output_dir,
  recursive = TRUE,
  showWarnings = FALSE
)

method_levels <- c(
  "Assimilated",
  "LME",
  "REACHES"
)

method_colors <- c(
  "Assimilated" = "#F8766D",
  "LME" = "#00BA38",
  "REACHES" = "#619CFF"
)

method_shapes <- c(
  "Assimilated" = 16,
  "LME" = 17,
  "REACHES" = 15
)

base_text_size <- 23
correlation_text_size <- 6.5
legend_text_size <- 18

# ------------------------------------------------------------
# 2. Read the GHCN workbook
#
# The workbook contains repeating value/flag columns. Preserve
# the original selection of year plus 12 monthly temperatures.
# ------------------------------------------------------------

if (!file.exists(
  ghcn_file
)) {
  stop(
    "GHCN workbook was not found: ",
    ghcn_file
  )
}

ghcn_column_types <- c(
  "skip", "numeric", "skip",
  "numeric", "skip", "skip",
  "numeric", "skip", "skip",
  "numeric", "skip", "skip",
  "numeric", "skip", "skip",
  "numeric", "skip", "skip",
  "numeric", "skip", "skip",
  "numeric", "skip", "skip",
  "numeric", "skip", "skip",
  "numeric", "skip", "skip",
  "numeric", "skip", "skip",
  "numeric", "skip", "skip",
  "numeric", "skip", "skip"
)

ghcn_all <- readxl::read_excel(
  ghcn_file,
  col_types = ghcn_column_types
)

if (ncol(
  ghcn_all
) != 13L) {
  stop(
    "Expected one GHCN year column and 12 monthly columns, ",
    "but found ",
    ncol(
      ghcn_all
    ),
    " columns."
  )
}

names(
  ghcn_all
) <- c(
  "year",
  paste0(
    "month",
    1:12
  )
)

# ------------------------------------------------------------
# 3. City configuration
# ------------------------------------------------------------

city_config <- list(
  Beijing = list(
    row_indices = 1:161,
    remove_local_rows = c(
      103,
      104
    ),
    validation_file = file.path(
      validation_dir,
      "assimilation_Beijing.csv"
    ),
    output_file = file.path(
      output_dir,
      "Figure10a.png"
    )
  ),
  Shanghai = list(
    row_indices = 443:503,
    remove_local_rows = integer(
      0
    ),
    validation_file = file.path(
      validation_dir,
      "assimilation_Shanghai.csv"
    ),
    output_file = file.path(
      output_dir,
      "Figure10b.png"
    )
  ),
  HongKong = list(
    row_indices = 839:895,
    remove_local_rows = integer(
      0
    ),
    validation_file = file.path(
      validation_dir,
      "assimilation_HongKong.csv"
    ),
    output_file = file.path(
      output_dir,
      "Figure10c.png"
    )
  )
)

# ------------------------------------------------------------
# 4. Helper functions
# ------------------------------------------------------------

prepare_ghcn_city <- function(
    ghcn_data,
    row_indices,
    remove_local_rows,
    city_name) {

  if (
    length(
      row_indices
    ) == 0L ||
      max(
        row_indices
      ) >
        nrow(
          ghcn_data
        )
  ) {
    stop(
      "The configured GHCN row range for ",
      city_name,
      " is invalid."
    )
  }

  city_data <- ghcn_data[
    row_indices,
    ,
    drop = FALSE
  ]

  if (length(
    remove_local_rows
  ) > 0L) {

    if (
      min(
        remove_local_rows
      ) < 1L ||
        max(
          remove_local_rows
        ) >
          nrow(
            city_data
          )
    ) {
      stop(
        "A configured GHCN row removal for ",
        city_name,
        " is invalid."
      )
    }

    city_data <- city_data[
      -remove_local_rows,
      ,
      drop = FALSE
    ]
  }

  monthly_values <- as.matrix(
    city_data[
      ,
      paste0(
        "month",
        1:12
      ),
      drop = FALSE
    ]
  )

  storage.mode(
    monthly_values
  ) <- "double"

  # Retain only years with all 12 monthly temperatures.
  complete_months <- rowSums(
    is.na(
      monthly_values
    )
  ) == 0L

  annual_temperature <- rowMeans(
    monthly_values,
    na.rm = TRUE
  ) /
    100

  result <- data.frame(
    year = as.integer(
      city_data$year[
        complete_months
      ]
    ),
    GHCN = as.numeric(
      annual_temperature[
        complete_months
      ]
    )
  ) %>%
    arrange(
      year
    )

  if (
    anyNA(
      result
    ) ||
      any(!is.finite(
        result$GHCN
      )) ||
      anyDuplicated(
        result$year
      )
  ) {
    stop(
      "Invalid annual GHCN values were produced for ",
      city_name,
      "."
    )
  }

  result
}

read_validation_data <- function(
    filename,
    city_name) {

  if (!file.exists(
    filename
  )) {
    stop(
      "Validation file for ",
      city_name,
      " was not found: ",
      filename,
      "\nRun Code/Figure9d.R first."
    )
  }

  validation_data <- readr::read_csv(
    filename,
    show_col_types = FALSE
  )

  # Prefer the explicit names produced by the revised Figure9d.R.
  revised_columns <- c(
    "year",
    "smoothed_temperature_celsius",
    "calibrated_reaches_celsius",
    "lme_ensemble_mean_celsius"
  )

  # Retain support for older archived validation files.
  legacy_columns <- c(
    "year",
    "predicted",
    "REACHES",
    "LME"
  )

  if (all(
    revised_columns %in%
      names(
        validation_data
      )
  )) {

    validation_data <- validation_data %>%
      transmute(
        year = as.integer(
          year
        ),
        Assimilated = as.numeric(
          smoothed_temperature_celsius
        ),
        REACHES = as.numeric(
          calibrated_reaches_celsius
        ),
        LME = as.numeric(
          lme_ensemble_mean_celsius
        )
      )

  } else if (all(
    legacy_columns %in%
      names(
        validation_data
      )
  )) {

    warning(
      "Using legacy validation column names for ",
      city_name,
      ". Regenerate this file with Code/Figure9d.R."
    )

    validation_data <- validation_data %>%
      transmute(
        year = as.integer(
          year
        ),
        Assimilated = as.numeric(
          predicted
        ),
        REACHES = as.numeric(
          REACHES
        ),
        LME = as.numeric(
          LME
        )
      )

  } else {

    stop(
      filename,
      " must contain either the revised columns:\n  ",
      paste(
        revised_columns,
        collapse = ", "
      ),
      "\nor the legacy columns:\n  ",
      paste(
        legacy_columns,
        collapse = ", "
      ),
      "."
    )
  }

  if (
    anyNA(
      validation_data$year
    ) ||
      anyDuplicated(
        validation_data$year
      )
  ) {
    stop(
      "The validation file contains invalid or duplicated years ",
      "for ",
      city_name,
      "."
    )
  }

  validation_data %>%
    arrange(
      year
    )
}

prepare_common_comparison_data <- function(
    validation_data,
    ghcn_data,
    city_name) {

  joined_data <- inner_join(
    validation_data,
    ghcn_data,
    by = "year"
  )

  # The reviewer requested comparisons at identical years.
  # Therefore, retain only the intersection where all four
  # absolute-temperature series are finite.
  common_data <- joined_data %>%
    filter(
      is.finite(
        GHCN
      ),
      is.finite(
        Assimilated
      ),
      is.finite(
        LME
      ),
      is.finite(
        REACHES
      )
    ) %>%
    arrange(
      year
    )

  if (nrow(
    common_data
  ) < 2L) {
    stop(
      "Fewer than two common complete comparison years were ",
      "found for ",
      city_name,
      "."
    )
  }

  common_data
}

make_long_plot_data <- function(
    common_data,
    city_name) {

  common_data %>%
    pivot_longer(
      cols = all_of(
        method_levels
      ),
      names_to = "Method",
      values_to = "Estimate"
    ) %>%
    mutate(
      city = city_name,
      Method = factor(
        Method,
        levels = method_levels
      )
    )
}

compute_method_metrics <- function(
    plot_data,
    city_name) {

  plot_data %>%
    group_by(
      Method
    ) %>%
    summarise(
      city = city_name,
      number_of_years = n(),
      first_year = min(
        year
      ),
      last_year = max(
        year
      ),
      correlation = cor(
        GHCN,
        Estimate
      ),
      mean_bias_estimate_minus_GHCN = mean(
        Estimate -
          GHCN
      ),
      RMSE = sqrt(
        mean(
          (
            Estimate -
              GHCN
          )^2
        )
      ),
      anomaly_correlation = cor(
        Estimate -
          mean(
            Estimate
          ),
        GHCN -
          mean(
            GHCN
          )
      ),
      anomaly_RMSE = sqrt(
        mean(
          (
            (
              Estimate -
                mean(
                  Estimate
                )
            ) -
              (
                GHCN -
                  mean(
                    GHCN
                  )
              )
          )^2
        )
      ),
      .groups = "drop"
    ) %>%
    mutate(
      Method = factor(
        Method,
        levels = method_levels
      )
    ) %>%
    arrange(
      Method
    )
}

make_square_limits <- function(
    plot_data,
    padding_fraction = 0.05) {

  value_range <- range(
    c(
      plot_data$GHCN,
      plot_data$Estimate
    ),
    finite = TRUE
  )

  value_span <- diff(
    value_range
  )

  if (
    !is.finite(
      value_span
    ) ||
      value_span <= 0
  ) {
    value_span <- max(
      abs(
        value_range
      ),
      1
    )
  }

  padding <- padding_fraction *
    value_span

  c(
    value_range[
      1
    ] -
      padding,
    value_range[
      2
    ] +
      padding
  )
}

make_correlation_labels <- function(
    metrics,
    plot_limits) {

  plot_span <- diff(
    plot_limits
  )

  metrics %>%
    arrange(
      Method
    ) %>%
    mutate(
      label = paste0(
        Method,
        ": Cor = ",
        formatC(
          correlation,
          format = "f",
          digits = 2
        )
      ),
      x =
        plot_limits[
          1
        ] +
        0.03 *
          plot_span,
      y =
        plot_limits[
          2
        ] -
        c(
          0.05,
          0.12,
          0.19
        ) *
          plot_span
    )
}

make_scatter_plot <- function(
    plot_data,
    correlation_labels,
    plot_limits) {

  ggplot(
    plot_data,
    aes(
      x = GHCN,
      y = Estimate,
      colour = Method,
      shape = Method
    )
  ) +
    geom_point(
      size = 3.5,
      alpha = 0.85
    ) +
    geom_abline(
      intercept = 0,
      slope = 1,
      linetype = "dashed",
      colour = "red",
      linewidth = 0.8
    ) +
    geom_text(
      data = correlation_labels,
      aes(
        x = x,
        y = y,
        label = label,
        colour = Method
      ),
      inherit.aes = FALSE,
      show.legend = FALSE,
      hjust = 0,
      size = correlation_text_size
    ) +
    scale_colour_manual(
      values = method_colors,
      breaks = method_levels
    ) +
    scale_shape_manual(
      values = method_shapes,
      breaks = method_levels
    ) +
    coord_equal(
      xlim = plot_limits,
      ylim = plot_limits
    ) +
    labs(
      x = expression(
        "GHCN temperature (" *
          degree *
          "C)"
      ),
      y = expression(
        "Estimated temperature (" *
          degree *
          "C)"
      ),
      colour = NULL,
      shape = NULL
    ) +
    theme_bw() +
    theme(
      text = element_text(
        size = base_text_size
      ),
      legend.title = element_blank(),
      legend.position = "bottom",
      legend.text = element_text(
        size = legend_text_size
      )
    )
}

# ------------------------------------------------------------
# 5. Generate Figure 10(a)--(c)
# ------------------------------------------------------------

figure10_plots <- vector(
  "list",
  length(
    city_config
  )
)

names(
  figure10_plots
) <- names(
  city_config
)

metric_tables <- vector(
  "list",
  length(
    city_config
  )
)

names(
  metric_tables
) <- names(
  city_config
)

plot_data_tables <- vector(
  "list",
  length(
    city_config
  )
)

names(
  plot_data_tables
) <- names(
  city_config
)

for (
  city_name in names(
    city_config
  )
) {

  config <- city_config[[city_name]]

  ghcn_city <- prepare_ghcn_city(
    ghcn_data = ghcn_all,
    row_indices = config$row_indices,
    remove_local_rows =
      config$remove_local_rows,
    city_name = city_name
  )

  validation_data <- read_validation_data(
    filename =
      config$validation_file,
    city_name = city_name
  )

  common_data <-
    prepare_common_comparison_data(
      validation_data =
        validation_data,
      ghcn_data = ghcn_city,
      city_name = city_name
    )

  plot_data <- make_long_plot_data(
    common_data = common_data,
    city_name = city_name
  )

  metrics <- compute_method_metrics(
    plot_data = plot_data,
    city_name = city_name
  )

  plot_limits <- make_square_limits(
    plot_data
  )

  correlation_labels <-
    make_correlation_labels(
      metrics = metrics,
      plot_limits = plot_limits
    )

  plot_object <- make_scatter_plot(
    plot_data = plot_data,
    correlation_labels =
      correlation_labels,
    plot_limits = plot_limits
  )

  figure10_plots[[city_name]] <- plot_object

  metric_tables[[city_name]] <- metrics

  plot_data_tables[[city_name]] <- plot_data

  ggsave(
    filename = config$output_file,
    plot = plot_object,
    width = 6,
    height = 6,
    units = "in",
    dpi = 300
  )

  message(
    "Saved ",
    city_name,
    ": ",
    config$output_file,
    " using ",
    nrow(
      common_data
    ),
    " common years."
  )
}

# ------------------------------------------------------------
# 6. Save metrics and exact plotting data
# ------------------------------------------------------------

figure10_metrics <- bind_rows(
  metric_tables
) %>%
  mutate(
    Method = as.character(
      Method
    )
  )

figure10_plot_data <- bind_rows(
  plot_data_tables
) %>%
  mutate(
    Method = as.character(
      Method
    )
  )

readr::write_csv(
  figure10_metrics,
  file.path(
    output_dir,
    "Figure10_metrics.csv"
  )
)

# Preserve a correlation-only file for compatibility with the
# previous workflow.
readr::write_csv(
  figure10_metrics %>%
    dplyr::select(
      city,
      method = Method,
      correlation
    ),
  file.path(
    output_dir,
    "Figure10_correlations.csv"
  )
)

readr::write_csv(
  figure10_plot_data,
  file.path(
    output_dir,
    "Figure10_plot_data.csv"
  )
)

message(
  "Completed Figure 10(a), Figure 10(b), and Figure 10(c)."
)

message(
  "Full correlation, bias, RMSE, and anomaly metrics saved to: ",
  file.path(
    output_dir,
    "Figure10_metrics.csv"
  )
)
