here::i_am("Code/Supplementary/FigureS3.R")

# ============================================================
# Generate Figure S3(a)--(c):
#   Figure S3(a): Beijing
#   Figure S3(b): Shanghai
#   Figure S3(c): Hong Kong
#
# Required inputs:
#   Data/GHCNv4.xlsx
#   Data/Valid/assimilation_Beijing.csv
#   Data/Valid/assimilation_Shanghai.csv
#   Data/Valid/assimilation_HongKong.csv
#
# The assimilation files are generated by Code/Figure9d.R and
# contain the complete annual Kalman filter/smoother output.
#
# Outputs:
#   Output/Supplementary/FigureS3a.png
#   Output/Supplementary/FigureS3b.png
#   Output/Supplementary/FigureS3c.png
#   Output/Supplementary/FigureS3_plot_data.csv
# ============================================================

library(readxl)
library(dplyr)
library(readr)
library(ggplot2)

ghcn_file <- here::here(
  "Data",
  "GHCNv4.xlsx"
)

validation_dir <- here::here(
  "Data",
  "Valid"
)

output_dir <- here::here(
  "Output",
  "Supplementary"
)

if (!file.exists(ghcn_file)) {
  stop("GHCN file was not found: ", ghcn_file)
}

dir.create(
  output_dir,
  recursive = TRUE,
  showWarnings = FALSE
)

ghcn_column_types <- c(
  "skip", "numeric", "skip",
  "numeric", "skip", "skip",
  "numeric", "skip", "skip",
  "numeric", "skip", "skip",
  "numeric", "skip", "skip",
  "numeric", "skip", "skip",
  "numeric", "skip", "skip",
  "numeric", "skip", "skip",
  "numeric", "skip", "skip",
  "numeric", "skip", "skip",
  "numeric", "skip", "skip",
  "numeric", "skip", "skip",
  "numeric", "skip", "skip"
)

ghcn_all <- readxl::read_excel(
  ghcn_file,
  col_types = ghcn_column_types
)

if (ncol(ghcn_all) != 13L) {
  stop(
    "Expected one year column and 12 monthly columns, but found ",
    ncol(ghcn_all),
    " columns."
  )
}

names(ghcn_all) <- c(
  "year",
  paste0("month", 1:12)
)

city_config <- list(
  Beijing = list(
    row_indices = 1:161,
    remove_local_rows = c(103, 104),
    start_year_exclusive = 1837,
    validation_file = file.path(
      validation_dir,
      "assimilation_Beijing.csv"
    ),
    output_file = file.path(
      output_dir,
      "FigureS3a.png"
    )
  ),
  Shanghai = list(
    row_indices = 443:503,
    remove_local_rows = integer(0),
    start_year_exclusive = 1847,
    validation_file = file.path(
      validation_dir,
      "assimilation_Shanghai.csv"
    ),
    output_file = file.path(
      output_dir,
      "FigureS3b.png"
    )
  ),
  HongKong = list(
    row_indices = 839:895,
    remove_local_rows = integer(0),
    start_year_exclusive = 1854,
    validation_file = file.path(
      validation_dir,
      "assimilation_HongKong.csv"
    ),
    output_file = file.path(
      output_dir,
      "FigureS3c.png"
    )
  )
)

series_colors <- c(
  "Assimilated" = "black",
  "REACHES" = "firebrick",
  "LME" = "deepskyblue",
  "GHCN" = "green3"
)

series_linetypes <- c(
  "Assimilated" = "solid",
  "REACHES" = "dashed",
  "LME" = "dotted"
)

legend_order <- c(
  "Assimilated",
  "GHCN",
  "LME",
  "REACHES"
)

prepare_ghcn_city <- function(
    ghcn_data,
    row_indices,
    remove_local_rows,
    city_name) {

  if (
    length(row_indices) == 0L ||
      min(row_indices) < 1L ||
      max(row_indices) > nrow(ghcn_data)
  ) {
    stop(
      "The configured GHCN row range for ",
      city_name,
      " is invalid."
    )
  }

  city_data <- ghcn_data[
    row_indices,
    ,
    drop = FALSE
  ]

  if (length(remove_local_rows) > 0L) {
    if (
      min(remove_local_rows) < 1L ||
        max(remove_local_rows) > nrow(city_data)
    ) {
      stop(
        "A configured row removal for ",
        city_name,
        " is invalid."
      )
    }

    city_data <- city_data[
      -remove_local_rows,
      ,
      drop = FALSE
    ]
  }

  monthly_values <- as.matrix(
    city_data[
      ,
      paste0("month", 1:12),
      drop = FALSE
    ]
  )

  storage.mode(monthly_values) <- "double"

  complete_year <- rowSums(
    is.na(monthly_values)
  ) == 0L

  annual_temperature <- rowMeans(
    monthly_values,
    na.rm = TRUE
  ) / 100

  result <- data.frame(
    year = as.integer(
      city_data$year[complete_year]
    ),
    GHCN = as.numeric(
      annual_temperature[complete_year]
    )
  ) %>%
    arrange(year)

  if (
    anyNA(result) ||
      any(!is.finite(result$GHCN)) ||
      anyDuplicated(result$year)
  ) {
    stop(
      "Invalid annual GHCN values were produced for ",
      city_name,
      "."
    )
  }

  result
}

read_validation_data <- function(
    filename,
    city_name) {

  if (!file.exists(filename)) {
    stop(
      "Assimilation file for ",
      city_name,
      " was not found: ",
      filename,
      "\nRun Code/Figure9d.R first."
    )
  }

  data <- readr::read_csv(
    filename,
    show_col_types = FALSE
  )

  required_columns <- c(
    "year",
    "smoothed_temperature_celsius",
    "smoothed_variance",
    "calibrated_reaches_celsius",
    "lme_ensemble_mean_celsius"
  )

  missing_columns <- setdiff(
    required_columns,
    names(data)
  )

  if (length(missing_columns) > 0L) {
    stop(
      filename,
      " is missing columns: ",
      paste(missing_columns, collapse = ", "),
      "."
    )
  }

  data <- data %>%
    transmute(
      year = as.integer(year),
      Assimilated = as.numeric(
        smoothed_temperature_celsius
      ),
      Assimilated_variance = as.numeric(
        smoothed_variance
      ),
      REACHES = as.numeric(
        calibrated_reaches_celsius
      ),
      LME = as.numeric(
        lme_ensemble_mean_celsius
      )
    ) %>%
    arrange(year)

  if (
    anyNA(data$year) ||
      any(!is.finite(data$Assimilated)) ||
      any(!is.finite(data$Assimilated_variance)) ||
      any(data$Assimilated_variance < 0) ||
      any(!is.finite(data$LME)) ||
      anyDuplicated(data$year)
  ) {
    stop(
      "Invalid annual assimilation values were found in ",
      filename,
      "."
    )
  }

  # Missing REACHES values are expected in non-event years.
  if (any(
    !is.na(data$REACHES) &
      !is.finite(data$REACHES)
  )) {
    stop(
      "Non-finite calibrated REACHES values were found in ",
      filename,
      "."
    )
  }

  data
}

prepare_plot_data <- function(
    validation_data,
    ghcn_data,
    start_year_exclusive,
    city_name) {

  validation_data <- validation_data %>%
    filter(
      year > start_year_exclusive,
      year <= 1911
    ) %>%
    mutate(
      Assimilated_sd = sqrt(
        Assimilated_variance
      ),
      lower_95 =
        Assimilated -
        1.96 * Assimilated_sd,
      upper_95 =
        Assimilated +
        1.96 * Assimilated_sd,
      city = city_name
    )

  ghcn_data <- ghcn_data %>%
    filter(
      year > start_year_exclusive,
      year <= 1911
    ) %>%
    mutate(
      city = city_name
    )

  if (nrow(validation_data) == 0L) {
    stop(
      "No annual model results between ",
      start_year_exclusive + 1,
      " and 1911 were found for ",
      city_name,
      "."
    )
  }

  if (nrow(ghcn_data) == 0L) {
    warning(
      "No complete GHCN years between ",
      start_year_exclusive + 1,
      " and 1911 were found for ",
      city_name,
      ". The annual model series will still be plotted."
    )
  }

  list(
    validation = validation_data,
    ghcn = ghcn_data
  )
}

make_time_series_plot <- function(
    validation_data,
    ghcn_data) {

  ggplot() +
    geom_ribbon(
      data = validation_data,
      aes(
        x = year,
        ymin = lower_95,
        ymax = upper_95
      ),
      fill = "grey30",
      alpha = 0.25
    ) +
    geom_line(
      data = validation_data,
      aes(
        x = year,
        y = Assimilated,
        colour = "Assimilated",
        linetype = "Assimilated"
      ),
      linewidth = 0.7,
      alpha = 0.75
    ) +
    geom_line(
      data = validation_data,
      aes(
        x = year,
        y = REACHES,
        colour = "REACHES",
        linetype = "REACHES"
      ),
      linewidth = 0.7,
      alpha = 0.75,
      na.rm = TRUE
    ) +
    geom_line(
      data = validation_data,
      aes(
        x = year,
        y = LME,
        colour = "LME",
        linetype = "LME"
      ),
      linewidth = 0.7,
      alpha = 0.75
    ) +
    geom_point(
      data = ghcn_data,
      aes(
        x = year,
        y = GHCN,
        colour = "GHCN"
      ),
      size = 0.7
    ) +
    scale_colour_manual(
      values = series_colors,
      breaks = legend_order
    ) +
    scale_linetype_manual(
      values = series_linetypes
    ) +
    labs(
      x = "Year",
      y = expression(
        "Temperature (" *
          degree *
          "C)"
      ),
      colour = NULL,
      linetype = NULL
    ) +
    theme(
      text = element_text(size = 12),
      legend.position = "bottom",
      legend.key.height = grid::unit(
        0.5,
        "cm"
      ),
      plot.title = element_text(
        hjust = 0.5
      )
    ) +
    guides(
      linetype = "none",
      colour = guide_legend(
        title = NULL,
        override.aes = list(
          linetype = c(
            "solid",
            "blank",
            "dotted",
            "dashed"
          ),
          shape = c(
            NA,
            16,
            NA,
            NA
          )
        )
      )
    )
}

figureS3_plots <- vector(
  "list",
  length(city_config)
)

names(figureS3_plots) <- names(
  city_config
)

plot_data_output <- vector(
  "list",
  length(city_config)
)

names(plot_data_output) <- names(
  city_config
)

for (city_name in names(city_config)) {

  config <- city_config[[city_name]]

  ghcn_city <- prepare_ghcn_city(
    ghcn_data = ghcn_all,
    row_indices = config$row_indices,
    remove_local_rows = config$remove_local_rows,
    city_name = city_name
  )

  validation_data <- read_validation_data(
    filename = config$validation_file,
    city_name = city_name
  )

  plot_data <- prepare_plot_data(
    validation_data = validation_data,
    ghcn_data = ghcn_city,
    start_year_exclusive =
      config$start_year_exclusive,
    city_name = city_name
  )

  message(
    city_name,
    ": annual model years = ",
    nrow(plot_data$validation),
    "; REACHES event years = ",
    sum(
      is.finite(
        plot_data$validation$REACHES
      )
    ),
    "; complete GHCN years = ",
    nrow(plot_data$ghcn)
  )

  plot_object <- make_time_series_plot(
    validation_data = plot_data$validation,
    ghcn_data = plot_data$ghcn
  )

  figureS3_plots[[city_name]] <- plot_object

  plot_data_output[[city_name]] <-
    plot_data$validation %>%
    left_join(
      plot_data$ghcn %>%
        dplyr::select(
          year,
          GHCN
        ),
      by = "year"
    )

  ggsave(
    filename = config$output_file,
    plot = plot_object,
    width = 6,
    height = 3,
    units = "in",
    dpi = 300
  )

  message(
    "Saved ",
    city_name,
    ": ",
    config$output_file
  )
}

readr::write_csv(
  bind_rows(plot_data_output),
  file.path(
    output_dir,
    "FigureS3_plot_data.csv"
  )
)

message(
  "Completed Figure S3(a)--(c)."
)
